name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files before deployment
        run: ls -la

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} "
            sudo rm -rf /home/${USER}/simple/*
            sudo mkdir -p /home/${USER}/simple
            sudo chown ${USER}:${USER} /home/${USER}/simple
          "

          rsync -avz --exclude='.git' --exclude='.github' -e "ssh -o StrictHostKeyChecking=no -i private_key" ./ ${USER}@${HOST}:/home/${USER}/simple/

          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} "
            sudo rm -rf /var/cache/nginx/*
            sudo systemctl restart nginx
          "

